[2025-07-02T12:29:21.474+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vehiculos_sri_etl_pipeline.extract_load_dim_tecnologia scheduled__2025-07-01T00:00:00+00:00 [queued]>
[2025-07-02T12:29:21.497+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vehiculos_sri_etl_pipeline.extract_load_dim_tecnologia scheduled__2025-07-01T00:00:00+00:00 [queued]>
[2025-07-02T12:29:21.498+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-07-02T12:29:21.526+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_load_dim_tecnologia> on 2025-07-01 00:00:00+00:00
[2025-07-02T12:29:21.547+0000] {standard_task_runner.py:57} INFO - Started process 113 to run task
[2025-07-02T12:29:21.555+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'vehiculos_sri_etl_pipeline', 'extract_load_dim_tecnologia', 'scheduled__2025-07-01T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/vehiculos_sri_etl.py', '--cfg-path', '/tmp/tmp2tvm47ok']
[2025-07-02T12:29:21.559+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask extract_load_dim_tecnologia
[2025-07-02T12:29:21.650+0000] {task_command.py:416} INFO - Running <TaskInstance: vehiculos_sri_etl_pipeline.extract_load_dim_tecnologia scheduled__2025-07-01T00:00:00+00:00 [running]> on host 1fa40a7dc483
[2025-07-02T12:29:21.777+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineer' AIRFLOW_CTX_DAG_ID='vehiculos_sri_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_load_dim_tecnologia' AIRFLOW_CTX_EXECUTION_DATE='2025-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-01T00:00:00+00:00'
[2025-07-02T12:29:21.782+0000] {vehiculos_sri_etl.py:138} INFO - Iniciando procesamiento de DIM_TECNOLOGIA
[2025-07-02T12:29:21.843+0000] {vehiculos_sri_etl.py:50} INFO - Clientes de GCP inicializados correctamente
[2025-07-02T12:29:23.452+0000] {vehiculos_sri_etl.py:68} ERROR - Error leyendo archivo raw-data/matriculaciones_2024.csv: 404 GET https://storage.googleapis.com/download/storage/v1/b/etl-vehiculos-sri/o/raw-data%2Fmatriculaciones_2024.csv?alt=media: The specified bucket does not exist.: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)
[2025-07-02T12:29:23.453+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 1099, in download_blob_to_file
    blob_or_uri._do_download(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 984, in _do_download
    response = download.consume(transport, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/resumable_media/requests/download.py", line 237, in consume
    return _request_helpers.wait_and_retry(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/resumable_media/requests/_request_helpers.py", line 155, in wait_and_retry
    response = func()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/resumable_media/requests/download.py", line 219, in retriable_request
    self._process_response(result)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/resumable_media/_download.py", line 188, in _process_response
    _helpers.require_status_code(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/resumable_media/_helpers.py", line 108, in require_status_code
    raise common.InvalidResponse(
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 404, 'Expected one of', 200, 206)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/vehiculos_sri_etl.py", line 143, in extract_and_load_dim_tecnologia
    df_main = read_csv_from_gcs(storage_client, BUCKET_NAME, 'raw-data/matriculaciones_2024.csv')
  File "/opt/airflow/dags/vehiculos_sri_etl.py", line 63, in read_csv_from_gcs
    content = blob.download_as_text()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 1612, in download_as_text
    data = self.download_as_bytes(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 1387, in download_as_bytes
    client.download_blob_to_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/client.py", line 1112, in download_blob_to_file
    _raise_from_invalid_response(exc)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 4373, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.NotFound: 404 GET https://storage.googleapis.com/download/storage/v1/b/etl-vehiculos-sri/o/raw-data%2Fmatriculaciones_2024.csv?alt=media: The specified bucket does not exist.: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)
[2025-07-02T12:29:23.478+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=vehiculos_sri_etl_pipeline, task_id=extract_load_dim_tecnologia, execution_date=20250701T000000, start_date=20250702T122921, end_date=20250702T122923
[2025-07-02T12:29:23.502+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task extract_load_dim_tecnologia (404 GET https://storage.googleapis.com/download/storage/v1/b/etl-vehiculos-sri/o/raw-data%2Fmatriculaciones_2024.csv?alt=media: The specified bucket does not exist.: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>); 113)
[2025-07-02T12:29:23.536+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-02T12:29:23.581+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
